#Configurar puerto
server:
    port: 8095
    servlet:
        context-path: /msmaestriac


# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://us-east.connect.psdb.cloud/tramites-db?sslMode=VERIFY_IDENTITY
    username: 2wchfr8cooh6b5sjyq80
    password: pscale_pw_TvpnCOSBD1QthbRt6kLnw2I89oi7IOKH0oTERlTzEeg
    driver-class-name: com.mysql.cj.jdbc.Driver


